const qs=(s,p=document)=>p.querySelector(s), qsa=(s,p=document)=>[...p.querySelectorAll(s)];
const header=qs('#header'),nav=qs('#nav'),menuBtn=qs('#menuBtn');
window.addEventListener('load',()=>setTimeout(()=>qs('#loader').classList.add('hide'),350));
window.addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>40),{passive:true});
menuBtn.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuBtn.classList.toggle('active',open);menuBtn.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open)});
qsa('.nav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuBtn.classList.remove('active');document.body.classList.remove('menu-open');menuBtn.setAttribute('aria-expanded','false')}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}}),{threshold:.12});qsa('.reveal').forEach(el=>observer.observe(el));
const counterObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,target=parseFloat(el.dataset.value),suffix=el.dataset.suffix||'',decimal=String(target).includes('.');let start=performance.now();function tick(now){const p=Math.min((now-start)/1100,1),v=target*(1-Math.pow(1-p,3));el.textContent=(decimal?v.toFixed(1):Math.round(v))+suffix;if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick);counterObserver.unobserve(el)}),{threshold:.55});qsa('.counter').forEach(el=>counterObserver.observe(el));
if(matchMedia('(min-width:981px) and (prefers-reduced-motion:no-preference)').matches){const cursor=qs('#cursor'),dot=qs('#cursorDot');window.addEventListener('mousemove',e=>{cursor.style.left=dot.style.left=e.clientX+'px';cursor.style.top=dot.style.top=e.clientY+'px'});qsa('a,button,.service-card').forEach(el=>{el.addEventListener('mouseenter',()=>cursor.classList.add('hover'));el.addEventListener('mouseleave',()=>cursor.classList.remove('hover'))});qsa('.magnetic').forEach(el=>{el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)*.13,y=(e.clientY-r.top-r.height/2)*.16;el.style.transform=`translate(${x}px,${y}px)`});el.addEventListener('mouseleave',()=>el.style.transform='')});window.addEventListener('scroll',()=>qsa('.parallax').forEach(el=>{const r=el.getBoundingClientRect(),s=parseFloat(el.dataset.speed||0.05);if(r.bottom>0&&r.top<innerHeight)el.style.transform=`translateY(${(innerHeight/2-(r.top+r.height/2))*s}px) scale(1.04)`}),{passive:true})}
const lightbox=qs('#lightbox'),lightboxImg=qs('#lightboxImg');qsa('.gallery-item').forEach(btn=>btn.addEventListener('click',()=>{lightboxImg.src=btn.dataset.image;lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}));function closeLightbox(){lightbox.classList.remove('open');lightbox.setAttribute('aria-hidden','true');document.body.style.overflow=''}qs('#lightboxClose').addEventListener('click',closeLightbox);lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeLightbox()});addEventListener('keydown',e=>{if(e.key==='Escape')closeLightbox()});
let reviewIndex=0;const track=qs('#reviewTrack'),cards=qsa('.review-card',track);function setReview(i){reviewIndex=(i+cards.length)%cards.length;track.style.transform=`translateX(-${reviewIndex*100}%)`}qs('#prevReview').addEventListener('click',()=>setReview(reviewIndex-1));qs('#nextReview').addEventListener('click',()=>setReview(reviewIndex+1));
qs('#bookingForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);const msg=`Здравствуйте! Хочу записаться в LOGOVO.%0A%0AИмя: ${encodeURIComponent(f.get('name'))}%0AТелефон: ${encodeURIComponent(f.get('phone'))}%0AФилиал: ${encodeURIComponent(f.get('branch'))}%0AУслуга: ${encodeURIComponent(f.get('service'))}%0AДата: ${encodeURIComponent(f.get('date'))}%0AВремя: ${encodeURIComponent(f.get('time'))}`;window.open(`https://wa.me/77003968940?text=${msg}`,'_blank','noopener')});
qs('#year').textContent=new Date().getFullYear();
